florida_townships = [
    'Alachua',
    'Altamonte Springs',
    'Anna Maria',
    'Apalachicola',
    'Apopka',
    'Atlantic Beach',
    'Auburndale',
    'Aventura',
    'Avon Park',
    'Bal Harbour',
    'Bartow',
    'Bay Harbor Islands',
    'Boca Raton',
    'Bonita Springs',
    'Boynton Beach',
    'Bradenton',
    'Brooksville',
    'Cape Canaveral',
    'Cape Coral',
    'Casselberry',
    'Celebration',
    'Chipley',
    'Cinco Bayou',
    'Clearwater',
    'Clewiston',
    'Cocoa',
    'Cocoa Beach',
    'Coconut Creek',
    'Coral Gables',
    'Coral Springs',
    'Crystal River',
    'Dania Beach',
    'Davie',
    'Daytona Beach',
    'Deerfield Beach',
    'DeFuniak Springs',
    'DeLand',
    'Delray Beach',
    'Deltona',
    'Destin',
    'Dunedin',
    'Eagle Lake',
    'Edgewater',
    'Edgewood',
    'Eustis',
    'Fort Lauderdale',
    'Fort Meade',
    'Fort Myers',
    'Fort Myers Beach',
    'Fort Pierce',
    'Fort Walton Beach',
    'Fruitland Park',
    'Gainesville',
    'Greenacres',
    'Green Cove Springs',
    'Gulf Breeze',
    'Gulfport',
    'Haines City',
    'Hallandale Beach',
    'Hawthorne',
    'Hialeah',
    'Hialeah Gardens',
    'Highland Beach',
    'Hollywood',
    'Holly Hill',
    'Holmes Beach',
    'Homestead',
    'Hypoluxo',
    'Indialantic',
    'Jacksonville',
    'Juno Beach',
    'Jupiter',
    'Key Biscayne',
    'Key West',
    'Kissimmee',
    'LaBelle',
    'Lady Lake',
    'Lake Alfred',
    'Lakeland',
    'Lake Mary',
    'Lake Park',
    'Lake Wales',
    'Lake Worth',
    'Lantana',
    'Largo',
    'Lauderdale By The Sea',
    'Lauderhill',
    'Leesburg',
    'Lighthouse Point',
    'Longboat Key',
    'Longwood',
    'Maitland',
    'Marco Island',
    'Margate',
    'Melbourne',
    'Melbourne Beach',
    'Miami',
    'Miami Beach',
    'Milton',
    'Minneola',
    'Miramar',
    'Mount Dora',
    'Naples',
    'Neptune Beach',
    'New Port Richey',
    'New Smyrna Beach',
    'Niceville',
    'North Miami',
    'North Miami Beach',
    'North Port',
    'Oakland Park',
    'Ocala',
    'Ocean Ridge',
    'Ocoee',
    'Okeechobee',
    'Oldsmar',
    'Orange Park',
    'Orlando',
    'Ormond Beach',
    'Oviedo',
    'Palatka',
    'Palm Bay',
    'Palm Beach',
    'Palm Beach Gardens',
    'Palm Coast',
    'Palmetto',
    'Panama City',
    'Panama City Beach',
    'Pembroke Pines',
    'Pensacola',
    'Pinecrest',
    'Pinellas Park',
    'Plant City',
    'Plantation',
    'Pompano Beach',
    'Ponce Inlet',
    'Port Orange',
    'Port St. Lucie',
    'Punta Gorda',
    'Rockledge',
    'Royal Palm Beach',
    'St. Augustine',
    'St. Augustine Beach',
    'St. Cloud',
    'St. Pete Beach',
    'St. Petersburg',
    'Safety Harbor',
    'Sanford',
    'Sanibel',
    'Sarasota',
    'Satellite Beach',
    'Seaside',
    'Sebastian',
    'Sewall\'s Point',
    'Shalimar',
    'Stuart',
    'Surfside',
    'Tallahassee',
    'Tamarac',
    'Tampa',
    'Tarpon Springs',
    'Tavares',
    'Temple Terrace',
    'Titusville',
    'Treasure Island',
    'Valparaiso',
    'Venice',
    'Vero Beach',
    'Wellington',
    'West Melbourne',
    'West Palm Beach',
    'Weston',
    'Wilton Manors',
    'Winter Garden',
    'Winter Haven',
    'Winter Park',
    'Winter Springs',
    ]
